#!/bin/sh
# cleanup
rm -rf obj_dir
rm -r Vtop.vcd


# run Verilator so we can translate .sv into .cpp, and pass this to our C++ testbench


verilator -Wall --cc --trace top.sv PC_mod.sv rom.sv --exe PC_tb.cpp

#build the C++ project through make automatically generated by verilator

make -j -C obj_dir/ -f Vtop.mk Vtop

#run the executable simulation file

obj_dir/Vtop


